version: '3.8'

services:
  webapplication1:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+80
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"  
