// <auto-generated />
using System;
using DataAccess.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240404151646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.ActivitySet.ActivityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Activities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Доклад, 35-45 минут",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Мастеркласс, 1-2 часа",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Дискуссия / круглый стол, 40-50 минут",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Entities.Application", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IsApproved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IsDraft")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OnViewing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApplicationId");

                    b.ToTable("Applications", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
